/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History: your analyses plus the public samples */
        get: operations["list_analyses_api_v1_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One analysis in full */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete one of your analyses
         * @description Soft delete: hidden from every read afterwards; the files stay on disk (P-07).
         */
        delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one image of an analysis
         * @description No ``X-Client-Id`` here: an ``<img>`` tag cannot send headers, so the signed
         *     link is the credential. Samples are public and need no signature.
         */
        get: operations["get_analysis_image_api_v1_analyses__analysis_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaf-disease/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identify healthy vs. diseased leaf tissue, and the disease type */
        post: operations["predict_leaf_disease_api_v1_leaf_disease_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaf-segmentation/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measure healthy vs damaged leaf tissue */
        post: operations["predict_leaf_segmentation_api_v1_leaf_segmentation_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List models and their status
         * @description All three models are built; `status: unavailable` means one failed to load at startup
         *     (missing weights, bad checkpoint), not a future model.
         *
         *     A pure in-memory read, so it runs on the event loop without a threadpool hop.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tree/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Is this a banana tree? */
        post: operations["predict_tree_api_v1_tree_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only — no DB/model checks, must always be fast.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisDetail */
        AnalysisDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Details */
            details: (components["schemas"]["TreeDetails"] | components["schemas"]["LeafSegDetails"] | components["schemas"]["LeafDiseaseDetails"]) | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            image: components["schemas"]["ImageLinks"];
            /** Is Sample */
            is_sample: boolean;
            /** @description Null when the client sent no coordinates, accuracy or capture time */
            location: components["schemas"]["GeoLocation"] | null;
            /**
             * Model Key
             * @enum {string}
             */
            model_key: "tree_classification" | "leaf_segmentation" | "leaf_disease";
            /** Model Version */
            model_version: string;
            prediction: components["schemas"]["Prediction"] | null;
            /**
             * Source
             * @enum {string}
             */
            source: "upload" | "camera" | "sample";
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "failed";
            timings_ms: components["schemas"]["TimingsMs"];
            /** Title */
            title?: string | null;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Label */
            display_label: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Sample */
            is_sample: boolean;
            /** Is Uncertain */
            is_uncertain: boolean;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Model Key
             * @enum {string}
             */
            model_key: "tree_classification" | "leaf_segmentation" | "leaf_disease";
            /**
             * Source
             * @enum {string}
             */
            source: "upload" | "camera" | "sample";
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Title */
            title?: string | null;
        };
        /** Body_predict_leaf_disease_api_v1_leaf_disease_predict_post */
        Body_predict_leaf_disease_api_v1_leaf_disease_predict_post: {
            /**
             * Captured At
             * @description ISO-8601 capture time; a time without an offset is read as UTC
             */
            captured_at?: string | null;
            /**
             * Gps Accuracy M
             * @description GPS accuracy in metres
             */
            gps_accuracy_m?: number | null;
            /**
             * Image
             * @description Photo to analyse (JPEG, PNG or WEBP)
             */
            image: string;
            /**
             * Latitude
             * @description Degrees, -90..90
             */
            latitude?: number | null;
            /**
             * Longitude
             * @description Degrees, -180..180
             */
            longitude?: number | null;
            /**
             * Source
             * @description Where the photo came from
             * @default upload
             * @enum {string}
             */
            source: "upload" | "camera";
        };
        /** Body_predict_leaf_segmentation_api_v1_leaf_segmentation_predict_post */
        Body_predict_leaf_segmentation_api_v1_leaf_segmentation_predict_post: {
            /**
             * Captured At
             * @description ISO-8601 capture time; a time without an offset is read as UTC
             */
            captured_at?: string | null;
            /**
             * Gps Accuracy M
             * @description GPS accuracy in metres
             */
            gps_accuracy_m?: number | null;
            /**
             * Image
             * @description Photo to analyse (JPEG, PNG or WEBP)
             */
            image: string;
            /**
             * Latitude
             * @description Degrees, -90..90
             */
            latitude?: number | null;
            /**
             * Longitude
             * @description Degrees, -180..180
             */
            longitude?: number | null;
            /**
             * Source
             * @description Where the photo came from
             * @default upload
             * @enum {string}
             */
            source: "upload" | "camera";
        };
        /** Body_predict_tree_api_v1_tree_predict_post */
        Body_predict_tree_api_v1_tree_predict_post: {
            /**
             * Captured At
             * @description ISO-8601 capture time; a time without an offset is read as UTC
             */
            captured_at?: string | null;
            /**
             * Gps Accuracy M
             * @description GPS accuracy in metres
             */
            gps_accuracy_m?: number | null;
            /**
             * Image
             * @description Photo to analyse (JPEG, PNG or WEBP)
             */
            image: string;
            /**
             * Latitude
             * @description Degrees, -90..90
             */
            latitude?: number | null;
            /**
             * Longitude
             * @description Degrees, -180..180
             */
            longitude?: number | null;
            /**
             * Source
             * @description Where the photo came from
             * @default upload
             * @enum {string}
             */
            source: "upload" | "camera";
        };
        /**
         * DiseaseChannelMetrics
         * @description Per-disease-channel measurements, one of these per entry in `LeafDiseaseDetails.diseases`.
         */
        DiseaseChannelMetrics: {
            /** Area Pct Of Leaf */
            area_pct_of_leaf: number;
            /**
             * Channel
             * @enum {string}
             */
            channel: "black_sigatoka" | "yellow_sigatoka";
            /** Largest Lesion Pct Of Leaf */
            largest_lesion_pct_of_leaf: number;
            /** Lesion Count */
            lesion_count: number;
            /** Mean Probability */
            mean_probability?: number | null;
        };
        /**
         * GeoLocation
         * @description Where and when the photo was taken, as reported by the client's device.
         *
         *     Every field is optional because the client may send any subset; the whole
         *     block is ``null`` on an analysis when it sent none of them.
         */
        GeoLocation: {
            /**
             * Accuracy M
             * @description GPS accuracy in metres
             */
            accuracy_m?: number | null;
            /**
             * Captured At
             * @description Client-reported capture time (UTC)
             */
            captured_at?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * ImageLinks
         * @description Relative URLs (the frontend prefixes its API base). Private images are signed
         *     and expire; sample images are public and need no signature.
         */
        ImageLinks: {
            /** Height */
            height?: number | null;
            /** Original Url */
            original_url: string;
            /**
             * Result Url
             * @description Overlay/mask image; only models that produce one
             */
            result_url?: string | null;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Width */
            width?: number | null;
        };
        /** LeafDiseaseDetails */
        LeafDiseaseDetails: {
            /**
             * Diagnosis
             * @enum {string}
             */
            diagnosis: "healthy" | "black_sigatoka" | "yellow_sigatoka" | "no_leaf";
            /** Diseases */
            diseases: components["schemas"]["DiseaseChannelMetrics"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "leaf_disease";
            /** Leaf Area Pct Of Image */
            leaf_area_pct_of_image: number;
            /** Mean Leaf Probability */
            mean_leaf_probability?: number | null;
            thresholds: components["schemas"]["LeafDiseaseThresholds"];
        };
        /**
         * LeafDiseaseThresholds
         * @description The exact policy that produced a result, echoed so a stored row is reproducible.
         */
        LeafDiseaseThresholds: {
            /**
             * Black Sigatoka
             * @description p(black_sigatoka) >= this -> affected pixel
             */
            black_sigatoka: number;
            /**
             * Leaf
             * @description p(leaf) >= this -> leaf pixel
             */
            leaf: number;
            /**
             * Min Disease Pct
             * @description a disease's share of the leaf (%) below which it is ignored
             */
            min_disease_pct: number;
            /**
             * Min Leaf Pct
             * @description leaf share of the image (%) below which the result is 'no_leaf'
             */
            min_leaf_pct: number;
            /**
             * Min Lesion Pct
             * @description lesion blobs smaller than this % of the leaf area are dropped
             */
            min_lesion_pct: number;
            /**
             * Tta Hflip
             * @description probabilities averaged with the horizontally flipped pass
             */
            tta_hflip: boolean;
            /**
             * Yellow Sigatoka
             * @description p(yellow_sigatoka) >= this -> affected pixel
             */
            yellow_sigatoka: number;
        };
        /** LeafSegDetails */
        LeafSegDetails: {
            /** Affected Area Pct Of Leaf */
            affected_area_pct_of_leaf: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "leaf_segmentation";
            /** Largest Lesion Pct Of Leaf */
            largest_lesion_pct_of_leaf: number;
            /** Leaf Area Pct Of Image */
            leaf_area_pct_of_image: number;
            /** Lesion Count */
            lesion_count: number;
            /** Mean Affected Probability */
            mean_affected_probability?: number | null;
            /** Mean Leaf Probability */
            mean_leaf_probability?: number | null;
            thresholds: components["schemas"]["LeafSegThresholds"];
        };
        /**
         * LeafSegThresholds
         * @description The exact policy that produced a result, echoed so a stored row is reproducible.
         */
        LeafSegThresholds: {
            /**
             * Affected
             * @description p(affected) >= this -> affected pixel
             */
            affected: number;
            /**
             * Leaf
             * @description p(leaf) >= this -> leaf pixel
             */
            leaf: number;
            /**
             * Min Affected Pct
             * @description affected share of the leaf (%) below which the leaf is 'healthy'
             */
            min_affected_pct: number;
            /**
             * Min Leaf Pct
             * @description leaf share of the image (%) below which the result is 'no_leaf'
             */
            min_leaf_pct: number;
            /**
             * Min Lesion Pct
             * @description lesion blobs smaller than this % of the leaf area are dropped
             */
            min_lesion_pct: number;
            /**
             * Tta Hflip
             * @description probabilities averaged with the horizontally flipped pass
             */
            tta_hflip: boolean;
        };
        /**
         * ModelInfoOut
         * @description One entry of ``GET /models`` — ``app.ml.base.ModelInfo`` plus ``is_placeholder``.
         */
        ModelInfoOut: {
            /** Classes */
            classes: string[];
            /** Display Name */
            display_name: string;
            /**
             * Is Placeholder
             * @description True while the weights are a randomly-initialised stand-in (not real results)
             */
            is_placeholder: boolean;
            /**
             * Key
             * @enum {string}
             */
            key: "tree_classification" | "leaf_segmentation" | "leaf_disease";
            /**
             * Reason
             * @description Why the model is unavailable (never contains file paths)
             */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
            /** Task */
            task: string;
            /** Version */
            version: string;
        };
        /** Page[AnalysisSummary] */
        Page_AnalysisSummary_: {
            /** Items */
            items: components["schemas"]["AnalysisSummary"][];
            /**
             * Page
             * @description 1-based page number
             */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Total
             * @description Number of matching items over all pages
             */
            total: number;
            /**
             * Total Pages
             * @description 0 when there are no matching items
             */
            total_pages: number;
        };
        /** Prediction */
        Prediction: {
            /**
             * Confidence
             * @description 0-1; null when the model has no single honest number
             */
            confidence: number | null;
            /**
             * Display Label
             * @description Human-readable label, or 'Uncertain'
             */
            display_label: string;
            /** Is Uncertain */
            is_uncertain: boolean;
            /**
             * Label
             * @description Raw class key produced by the model
             */
            label: string | null;
        };
        /**
         * ProblemDetail
         * @description RFC 9457 application/problem+json body shape (for OpenAPI docs).
         */
        ProblemDetail: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Errors */
            errors?: {
                [key: string]: string;
            }[] | null;
            /** Instance */
            instance: string;
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** TimingsMs */
        TimingsMs: {
            /** Inference */
            inference?: number | null;
            /** Postprocess */
            postprocess?: number | null;
            /** Preprocess */
            preprocess?: number | null;
            /**
             * Total
             * @description Wall-clock of the whole analysis
             */
            total?: number | null;
        };
        /** TreeDetails */
        TreeDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tree_classification";
            /** Probabilities */
            probabilities: components["schemas"]["TreeProbability"][];
            /** Threshold */
            threshold: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "banana_tree" | "not_banana_tree" | "uncertain";
        };
        /** TreeProbability */
        TreeProbability: {
            /** Class Key */
            class_key: string;
            /** Display Name */
            display_name: string;
            /** Probability */
            probability: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analyses_api_v1_analyses_get: {
        parameters: {
            query?: {
                /** @description Only this model */
                model_key?: ("tree_classification" | "leaf_segmentation" | "leaf_disease") | null;
                /** @description mine = your own, samples = public samples, all_visible = both */
                scope?: "mine" | "samples" | "all_visible";
                /** @description 1-based page number */
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AnalysisSummary_"];
                };
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found (also returned for another client's analysis — existence is never revealed). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_analysis_api_v1_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden: invalid or expired image signature, or the analysis is an immutable sample. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found (also returned for another client's analysis — existence is never revealed). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_analysis_image_api_v1_analyses__analysis_id__image_get: {
        parameters: {
            query?: {
                /** @description Which image */
                variant?: "original" | "thumbnail" | "result";
                /** @description Unix expiry time, from the signed URL */
                exp?: string | null;
                /** @description HMAC signature, from the signed URL */
                sig?: string | null;
            };
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description Forbidden: invalid or expired image signature, or the analysis is an immutable sample. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found (also returned for another client's analysis — existence is never revealed). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    predict_leaf_disease_api_v1_leaf_disease_predict_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_leaf_disease_api_v1_leaf_disease_predict_post"];
            };
        };
        responses: {
            /** @description Analysis created and stored. */
            201: {
                headers: {
                    /** @description Relative URL of the new analysis (GET it for later). */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The upload exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The image format is not supported. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded; see the Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    predict_leaf_segmentation_api_v1_leaf_segmentation_predict_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_leaf_segmentation_api_v1_leaf_segmentation_predict_post"];
            };
        };
        responses: {
            /** @description Analysis created and stored. */
            201: {
                headers: {
                    /** @description Relative URL of the new analysis (GET it for later). */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The upload exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The image format is not supported. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded; see the Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoOut"][];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    predict_tree_api_v1_tree_predict_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Anonymous per-device UUID v4 generated by the frontend (D-04). */
                "X-Client-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_tree_api_v1_tree_predict_post"];
            };
        };
        responses: {
            /** @description Analysis created and stored. */
            201: {
                headers: {
                    /** @description Relative URL of the new analysis (GET it for later). */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Bad request: missing/invalid X-Client-Id, or the image is invalid or too small. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The upload exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The image format is not supported. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded; see the Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected server error or the model failed during inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The model or the database is currently unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
