import leafAnalysisSpecimenImg from '../assets/images/banana_leaf_analysis_1790753633840.jpg';
import model1ClassBalanceImg from '../assets/images/model1/04_class_counts_grouped_split.png';
import model1OversamplingImg from '../assets/images/model1/05_oversampling_effect.png';
import model1OptimizerSweepImg from '../assets/images/model1/06_optimizer_sweep.png';
import model1TrainingCurvesImg from '../assets/images/model1/07_training_curves.png';
import model1ConfusionMatrixImg from '../assets/images/model1/08_confusion_matrix.png';
import dronePlantDetectionImg from '../assets/images/future-scope/drone_field_detection.jpg';
import droneDiseaseDiagnosisImg from '../assets/images/future-scope/drone_disease_diagnostics.jpg';
import model2PixelCoverageImg from '../assets/images/model2/02_pixel_coverage_distribution.png';
import model2OptimizerSweepImg from '../assets/images/model2/04_optimizer_sweep.png';
import model2TrainingCurvesImg from '../assets/images/model2/05_training_curves.png';
import model2ThresholdSweepImg from '../assets/images/model2/06_threshold_sweep.png';
import model2ConfusionMatrixImg from '../assets/images/model2/07_confusion_matrix.png';
import model3LabelDistributionImg from '../assets/images/model3/01_disease_label_distribution.png';
import model3OptimizerSweepImg from '../assets/images/model3/04_optimizer_sweep.png';
import model3TrainingCurvesImg from '../assets/images/model3/05_training_curves.png';
import model3ThresholdSweepImg from '../assets/images/model3/06_per_channel_threshold_sweep.png';
import model3ConfusionMatrixImg from '../assets/images/model3/07_diagnosis_confusion_matrix.png';

export const ASSETS = {
  logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtNMR6qFPrbLCRmlFxcZKR9uWD45l3SbUOBGWfjQCmEn4mlPFaaF8INPgv1Zc0tpwc_0J-2tpe_bHE8tNWTHBPM793B8dz8V83DlXGoNHFUuW0GVW0sXHXC654c-v7KVXpBG-q_c-r0p4zSwrOCTwQ8bmAm6FJvSXSU9lmBKcXk6w24qjR_O4C9GaDTRXRdHs1li51sMjGyzme6C4GBjFx_qHwSX61cvga7gjoi61UdcRYoMJzRKeG',
  bananaTreeConfirmed: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbRvyb2frm-5XBAjuDOBGVz03JpJaukoca8A2xpJBod55GWlkmUFFCQUSvYc8yzAo3nlX48jve_Ft_aU2XoujCV_pZkvgWC8f2oRxTl0cWZmYOYMrfeT07oIYkBak9PQoiLA2BQHMVMC2d1cy45P-O3ew1F2x98Nb9Paar81T2iQRF0Yf4FWsSwxQZorp1yYdaWB-M2UIiFFdpaDyHwe3JeYOdAVTzbfssE_lWXyKoWr86tVgTJg_B',
  bananaFieldCalib: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdm7Qk1dHzS0nIQ36zKgbhsYdnJnebVKZYbFl2N1PjXGwGHBav8J8ryBUI_XZIxiRPU5IARRXiu49fykDxlBuq7hUuGx_zM3nJkUCQwNfKWoWk9ByMmyQUYAWvUM-viY4p5-Okf5u2MwS8kgb9u94kimqGPZRQ2GuI4POOeXruY6ylYIWRLyMdkNnedNSY_4YcNgSEE5AaESsBOnmGLD5O4yRCKvou3BqcCuqFC7rRKrU9qu6Z4Iei',
  viewfinderBanana: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXtQu3O79YKWQRngtZPQYJyh4dQdwviTv4pmT1h7iOlpWaROkgLttXe-bagwAwzNSTAUTMHpCDA5ygixYRGlKjn7eSAG5Nu3XVnvcpCJFkLAXIbxcxDEg1xO2XHzvw8bwyLTeN9T8JU8wXBkdeqBxEmvJQGj4heGeylNcXawseIEgspQD1rGruXj_YK8lpcl7PIqRU4cGIW9yriaoxexB5EnG4SuU3uSGjrfRVdPcAd_K2fueVrRvb',
  sigatokaLeafSample: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhH-9bXZLMQbi-EbqkzGcp6N8DFwIlxZLcBTwrV0bdyvsMYQqWjSkOaYTICBt3mVYn2SG4TIlITX_kUk7XzfKsC4HYMyu1wDqIeKMd3kfMO-tdUpQoxk7VkoEJgG0k5PrevrpFsCN1TLArk6QC0CneZlvKMDjF51HWLWA0ks9mkts9eQieUOMNXPvKF0X91lGFH1CVExut0YZrBpTa6IvpmBISRQXoc7DuatkdS9vnqTBllPEo-Tge',
  healthyLeafControl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChmrE0oLdUJj4jrSHq4z7WI-4eXCusjIjZsiF-Gh-BucimvzxARG7DN8ETE9o4BqKZNnfogiYSIxR7yFUHYJsu08ok6kSdaVCUKwRgZ2QV9uhyZDMI4rfuCjZ8ax6zzVSWV8KOe5ahspceTrogCjGWEdV9sQjSfM5Vkal8IgSZt1hvlheIYZqi5chMNOE2nMRymOOlp9s5y1OKJHSwPbAMAehQzt_U2wmfgcI2ARIAmEmrjMGvaauk',
  negativeHouseplant: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkhi7GQCKLsstdaYmyF-TYeebRrKrV4GpW6JUECsSDm6oJzFD7qd4v8tftUbP7V7XejUeFekwiZlK7wAo_tRCtFRtLJ6xTDBugCwje6GYXaHNCpN7MKVIEtOrGTT0AfNxcNXMa4OaE3JykJOUwxzXIvoanKpWm5dZhEWUkpLqLd0vWLaTrvPsc6dhTqAV1E9pwXNPOFFaCQsIvk3Q6m99aTYtx3Jp-kwXFQ-MwIVm27bB3ki70AlSf',
  leafAnalysisSpecimen: leafAnalysisSpecimenImg,
  // Real figures generated by experiment/01_tree_classification.ipynb (Model 1's actual
  // training run) — not mockups. See Backend/docs/adr/0013-model1-stays-a-classifier.md.
  model1ClassBalance: model1ClassBalanceImg,
  model1Oversampling: model1OversamplingImg,
  model1OptimizerSweep: model1OptimizerSweepImg,
  model1TrainingCurves: model1TrainingCurvesImg,
  model1ConfusionMatrix: model1ConfusionMatrixImg,
  // Future-scope concept art (drone-based farm surveillance), owner-supplied.
  droneSurveyPlantDetection: dronePlantDetectionImg,
  droneSurveyDiseaseDiagnosis: droneDiseaseDiagnosisImg,
  // Real figures generated by experiment/02_leaf_segmentation.ipynb (Model 2's actual
  // training run) — not mockups. See Backend/docs/adr/0012-model2-pipeline-and-contract.md.
  model2PixelCoverage: model2PixelCoverageImg,
  model2OptimizerSweep: model2OptimizerSweepImg,
  model2TrainingCurves: model2TrainingCurvesImg,
  model2ThresholdSweep: model2ThresholdSweepImg,
  model2ConfusionMatrix: model2ConfusionMatrixImg,
  // Real figures generated by experiment/03_leaf_disease_segmentation.ipynb (Model 3's actual
  // training run) — not mockups. See Backend/docs/adr/0019-model3-leaf-disease-pipeline-and-contract.md.
  model3LabelDistribution: model3LabelDistributionImg,
  model3OptimizerSweep: model3OptimizerSweepImg,
  model3TrainingCurves: model3TrainingCurvesImg,
  model3ThresholdSweep: model3ThresholdSweepImg,
  model3ConfusionMatrix: model3ConfusionMatrixImg,
};

// Real datasets this project actually trains on (verified against the raw files, not
// assumed from filenames — see experiment/README.md's "Data audit" section). No DOIs:
// these are private Roboflow exports, not published benchmarks, so none is claimed.
export const benchmarkDatasets = [
  {
    name: 'Banana Tree Detection (Roboflow export)',
    samples: '708 images',
    classes: 'Banana, Non-Banana (binary, used for Model 1)',
    resolution: 'Variable, re-split by capture session to remove leakage',
    source: 'Roboflow — private project export',
  },
  {
    name: 'Leaf Segmentation (Roboflow export)',
    samples: '161 images',
    classes: 'Leaf_boundary + one of {healthy_leaf, black_sigatoka_disease, cordana, yellow_sigatoka}',
    resolution: '432 × 432 px RGB (source), resized to 512 × 512 for training',
    source: 'Roboflow — private project export',
  },
  {
    name: 'Leaf Disease Identification (Roboflow export)',
    samples: '159 images',
    classes: 'Leaf_boundary + one of {black_sigatoka, yellow_sigatoka} (cordana and 1 unlabeled image excluded)',
    resolution: '432 × 432 px RGB (source), resized to 512 × 512 for training',
    source: 'Roboflow — private project export (same source as Leaf Segmentation)',
  },
];
