from __future__ import annotations

import uuid
from collections.abc import Iterator
from typing import Annotated

from fastapi import Depends, Header, Request
from sqlalchemy.orm import Session

from app.core.config import Settings, get_settings
from app.core.errors import InvalidClientIdError, MissingClientIdError
from app.db import session as db_session
from app.ml.registry import ModelRegistry
from app.services.analysis_service import AnalysisService
from app.storage.base import ImageStorage

SettingsDep = Annotated[Settings, Depends(get_settings)]


def get_db(request: Request) -> Iterator[Session]:
    """Per-request DB session (the factory is built in the app lifespan).

    The service commits; this dependency only guarantees rollback + close.
    """
    yield from db_session.get_db(request.app.state.session_factory)


DbSession = Annotated[Session, Depends(get_db)]


def get_client_id(
    # Declared as a Header parameter (rather than read off the Request) so that
    # /docs shows it on every route that needs it. It is optional *here* only so
    # that a missing header becomes our 400 MISSING_CLIENT_ID instead of FastAPI's
    # generic 422.
    x_client_id: Annotated[
        str | None,
        Header(
            alias="X-Client-Id",
            description="Anonymous per-device UUID v4 generated by the frontend (D-04).",
        ),
    ] = None,
) -> uuid.UUID:
    """The caller's anonymous device id (D-04). NOT authentication (spec 12)."""
    if x_client_id is None or not x_client_id.strip():
        raise MissingClientIdError()
    try:
        client_id = uuid.UUID(x_client_id.strip())
    except ValueError:
        raise InvalidClientIdError() from None
    # Spec 10 says uuid4. Enforcing the version also rejects the nil UUID and
    # sequential ids, which would be trivially guessable "history keys".
    if client_id.version != 4:
        raise InvalidClientIdError()
    return client_id


ClientId = Annotated[uuid.UUID, Depends(get_client_id)]


def get_registry(request: Request) -> ModelRegistry:
    """The model registry built in the app lifespan (or injected by tests)."""
    registry: ModelRegistry = request.app.state.registry
    return registry


Registry = Annotated[ModelRegistry, Depends(get_registry)]


def get_storage(request: Request) -> ImageStorage:
    """Local-disk image storage rooted at DATA_ROOT, created once in the lifespan."""
    storage: ImageStorage = request.app.state.storage
    return storage


Storage = Annotated[ImageStorage, Depends(get_storage)]


def get_analysis_service(
    session: DbSession,
    registry: Registry,
    storage: Storage,
    settings: SettingsDep,
) -> AnalysisService:
    return AnalysisService(session, registry, storage, settings)


AnalysisServiceDep = Annotated[AnalysisService, Depends(get_analysis_service)]
